### ISSUE TITLE
Output percentage progress when streaming a file

### ISSUE THREAD

**Issue by matthova** [markwal/GPX#18]
Curious how easy it would be to output percentage progress, either with a flag or with the verbose flag. Or is there an easier alternative to track the progress of a file being streamed?

**Comment by markwal** [comment]
Actually gpx wasn't intended to be a gcode sender and it lacks many features of such a thing including displaying progress, but also pause, cancel, terminal input, temperature indication, etc.  It's usually used offline to convert a file to x3g format.  The serial mode is usually used to send short messages from the command line to update the eeprom and the like or is orchestrated by another program like OctoPrint.

**Comment by markwal** [comment]
While this request is still outstanding, I'd like to close since there aren't any current plans to move the sender portion of GPX along.  The translated x3g can contain progress (GPX has a flag) and several senders also emit progress.
