### ISSUE TITLE
fcp machine type missing

### ISSUE THREAD

**Issue by jmacfarland** [markwal/GPX#26]
Installed latest on ubuntu 16.04, using apt install gpx.

when I run gpx, it shows the list of all commands/machine types/etc, but fcp is not on the list of machines.

**Comment by jmacfarland** [comment]
Note: fcp is still present in GpxUi.

**Comment by dnewman-polar3d** [comment]
Fcp is just an alias for r1d (Replicator 1 Dual).  Select r1d.

**Comment by jmacfarland** [comment]
Ah okay, thank you!

**Comment by markwal** [comment]
Also, the alias functionality of gpx is new for later versions.  I'm not sure what version you get through apt install at the moment.  The deb package is maintained by @hyperair.

**Comment by hyperair** [comment]
2.5.2 has been available for a while. https://launchpad.net/ubuntu/+source/gpx

**Comment by hyperair** [comment]
Hmm, I think xenial may not have it. You can get 2.5.2 for Ubuntu 16.04 from https://launchpad.net/~hyperair/+archive/ubuntu/3dprinter/+packages:

```sh
sudo add-apt-repository ppa:hyperair/3dprinter
sudo apt update
sudo apt install gpx
```

**Comment by jmacfarland** [comment]
That did it, thanks!
