### ISSUE TITLE
Steps per mm "Y-axis" no change

### ISSUE THREAD

**Issue by JKJameson** [markwal/GPX#27]
I have a Flashforge Creator Pro but seeing approx 5% loss in x and y measurements when using gcode instead of x3g.

I have fixed the x-axis by changing the default "Steps per mm" x-axis from 94.117647 to 96.53 but if I change the y-axis to this same value, or higher there is no observable change during the print for the y-axis.

fcp.ini
`[a]
[b]
[machine]
[x]
steps_per_mm=96.53
[y]
steps_per_mm=96.53
[z]`

**Comment by juan090988** [comment]
Have you encounter a solution for this problem?
