### ISSUE TITLE
Attempting to run gpx from command line 

### ISSUE THREAD

**Issue by jamesd256** [markwal/GPX#41]
Hi,

This may not be an issue, but unsure where to go to ask.  I would have thought with the output not showing any issues, the gcode would be received and acknowledged  by the printer.  GPX is running ok from the octoprint server on the same (pi) machine.  I installed gpx from the linux repositories rather than building it.

I'm trying this:

sudo gpx -v -c ./gpx.ini test.gcode /dev/ttyACM0 

The gpx.ini being used is attached here

[gpx.ini.txt](https://github.com/markwal/GPX/files/5286768/gpx.ini.txt)

test.gcode has G28 on a single line.  I've also tried M140 S60 to see if the printer will heat its bed.

Here is the output:

Loading config: gpx.ini
Loading machine definition: Replicator 1 - dual extruder
Loaded config: gpx.ini
Loading config: ./gpx.ini
Ignoring duplicate machine definition: -m r1d
Loaded config: ./gpx.ini
Reading from: test.gcode
Writing to: /dev/ttyACM0
Extrusion length: 0.000 metres
Estimated print time: 3 minutes 36 seconds
X3G output filesize: 29 bytes

**Comment by markwal** [comment]
GPX isn't really meant to be a host by itself.  It's just a translator.  That said, you can run it as a daemon and use another host to run gcode through it.  However, since you've already got GPX running with OctoPrint, you can just use OctoPrint to send your test.gcode to the printer, right?
